CREATE TABLE IF NOT EXISTS Prioritat (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Nom VARCHAR(100) NOT NULL,
	Color	VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Responsable (
	ID	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Nom	TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Tasca (
	ID	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Nom	TEXT NOT NULL,
	Descripcio TEXT,
	Data_creacio TEXT NOT NULL,
	Data_finalitzacio TEXT NOT NULL,
	Responsable INTEGER,
	Prioritat INTEGER,
	FOREIGN KEY(Prioritat) REFERENCES Prioritat(ID),
	FOREIGN KEY(Responsable) REFERENCES Responsable(ID)
);